# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - group19chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://group19bottest01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8b8af2266599468487a12d51797591e5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f8ec955065e4938969491851e2f2a97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: group19bottest01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8b8af2266599468487a12d51797591e5 }}/group19bottest01/group19bottest01image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'group19chatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5241e952107c4578802ce49b8643ec16 }}
        images: 'group19bottest01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8b8af2266599468487a12d51797591e5 }}/group19bottest01/group19bottest01image:${{ github.sha }}'